name: Run pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run pre-commit
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    env:
      PYTHON_VERSION: "3.10"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: x64
          cache: pip
      - name: Install pre-commit
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade "pre-commit>=2.13"
          python3 -m pre_commit install
      - name: Run pre-commit
        run: |
          python3 -m pre_commit run --show-diff-on-failure --color=always --all-files
